server:
  port: 8770


eureka:
  instance:
    hostname: eureka-server2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server1:8760/eureka/,http://eureka-server3:8780/eureka/
spring:
  profiles: eureka-server2